##
version: '3.9'
services:
    db:
        image: postgres:14.5
        restart: always
        environment:
            - POSTGRES_DB=bruvs_ningloo
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./db:/var/lib/postgresql/data
            - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
        ports:
            - 5432:5432
volumes:
    db:
        driver: local
